package:
  format-version: "1.0.0"
  name: "wireless_ble"
  type: "package"
  status: "production"
  required: false
  version: "v1.4.0"

  dependencies:
    - name: "wireless_pic32cxbz_wbz"
      type: "package"
      version: "v1.5.0"