package:
  format-version: "1.1.0"
  name: "wireless_ble"
  type: "package"
  status: "production"
  required: true
  version: "1.1.0"

  dependencies:
    - name: "wireless_pic32cxbz_wbz"
      type: "package"
      version: "1.2.0"