<#if TRCBS_ENABLE_CONFIG == true>
// Configuration of Service TRCBS
#define CONFIG_BLE_SVC_TRCBS_UUID_MCHP_PROPRIETARY_SERVICE_TRCB_16        ${CHECKED_TRCBS_SERVICE_UUID}    /* Service UUID */
#define CONFIG_BLE_SVC_TRCBS_UUID_MCHP_TRCB_L2CAP_PSM_16                  ${CHECKED_TRCBS_PSM_UUID}    /* PSM UUID */
#define CONFIG_BLE_SVC_TRCBS_UUID_MCHP_TRCB_CTRL_16                       ${CHECKED_TRCBS_CTRL_UUID}    /* CTRL UUID */
</#if>